### ISSUE TITLE
не работает Ваш чат

### ISSUE THREAD

**Issue by ViktorEresko** [ukevgen/BizareChat#98]
good!

**Comment by ViktorEresko** [comment]
с чердаком все в поряде интересно??

**Comment by akotsuba** [comment]
Hi @ViktorEresko. This project is a result of the Internship. For some of the developers this one is the first project in their life, so of course there are bugs and uncompleted features. If you are looking for the ready-to-use chat client, [here is the official Android client sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-chat) for the QuickBlox service.
